nav:
  home: /
  about: /about/
  articles: /archives/
  projects: https://github.com/ShineSmile

projects_url: https://github.com/ShineSmile

customize:
    gravatar:
        email: ShineSmile@outlook.com
    logo:
        enabled: true
        width: 45
        height: 45
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon.png
        gravator: false
      apple:
        url: /images/favicon.png
        gravator: false
    social_links:
    #    github: https://github.com/ShineSmile
    #    twitter: /
    #    facebook: /
    #    linkedin: /
    show_all_posts: true
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
